name: benchmark
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - xgboost
  - imbalanced-learn
  - joblib
  - tqdm
  - ipykernel
  - pip
  - pip:
      - hyperopt
      - transforms3d